name: 'Test Report'
on:
  workflow_run:
    workflows: ['Build & Test']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results
        name: XUnit Tests
        path: '**/*.trx'
        reporter: dotnet-trx